#include "../Includes/Utility.hpp"

#include <SFML/Graphics/Sprite.hpp>
#include <SFML/Graphics/Text.hpp>

#include <cmath>


std::string toString(sf::Keyboard::Key key)
{
	#define SNAKESFML_KEYTOSTRING_CASE(KEY) case sf::Keyboard::KEY: return #KEY;

	switch (key)
	{
		SNAKESFML_KEYTOSTRING_CASE(Unknown)
		SNAKESFML_KEYTOSTRING_CASE(A)
		SNAKESFML_KEYTOSTRING_CASE(B)
		SNAKESFML_KEYTOSTRING_CASE(C)
		SNAKESFML_KEYTOSTRING_CASE(D)
		SNAKESFML_KEYTOSTRING_CASE(E)
		SNAKESFML_KEYTOSTRING_CASE(F)
		SNAKESFML_KEYTOSTRING_CASE(G)
		SNAKESFML_KEYTOSTRING_CASE(H)
		SNAKESFML_KEYTOSTRING_CASE(I)
		SNAKESFML_KEYTOSTRING_CASE(J)
		SNAKESFML_KEYTOSTRING_CASE(K)
		SNAKESFML_KEYTOSTRING_CASE(L)
		SNAKESFML_KEYTOSTRING_CASE(M)
		SNAKESFML_KEYTOSTRING_CASE(N)
		SNAKESFML_KEYTOSTRING_CASE(O)
		SNAKESFML_KEYTOSTRING_CASE(P)
		SNAKESFML_KEYTOSTRING_CASE(Q)
		SNAKESFML_KEYTOSTRING_CASE(R)
		SNAKESFML_KEYTOSTRING_CASE(S)
		SNAKESFML_KEYTOSTRING_CASE(T)
		SNAKESFML_KEYTOSTRING_CASE(U)
		SNAKESFML_KEYTOSTRING_CASE(V)
		SNAKESFML_KEYTOSTRING_CASE(W)
		SNAKESFML_KEYTOSTRING_CASE(X)
		SNAKESFML_KEYTOSTRING_CASE(Y)
		SNAKESFML_KEYTOSTRING_CASE(Z)
		SNAKESFML_KEYTOSTRING_CASE(Num0)
		SNAKESFML_KEYTOSTRING_CASE(Num1)
		SNAKESFML_KEYTOSTRING_CASE(Num2)
		SNAKESFML_KEYTOSTRING_CASE(Num3)
		SNAKESFML_KEYTOSTRING_CASE(Num4)
		SNAKESFML_KEYTOSTRING_CASE(Num5)
		SNAKESFML_KEYTOSTRING_CASE(Num6)
		SNAKESFML_KEYTOSTRING_CASE(Num7)
		SNAKESFML_KEYTOSTRING_CASE(Num8)
		SNAKESFML_KEYTOSTRING_CASE(Num9)
		SNAKESFML_KEYTOSTRING_CASE(Escape)
		SNAKESFML_KEYTOSTRING_CASE(LControl)
		SNAKESFML_KEYTOSTRING_CASE(LShift)
		SNAKESFML_KEYTOSTRING_CASE(LAlt)
		SNAKESFML_KEYTOSTRING_CASE(LSystem)
		SNAKESFML_KEYTOSTRING_CASE(RControl)
		SNAKESFML_KEYTOSTRING_CASE(RShift)
		SNAKESFML_KEYTOSTRING_CASE(RAlt)
		SNAKESFML_KEYTOSTRING_CASE(RSystem)
		SNAKESFML_KEYTOSTRING_CASE(Menu)
		SNAKESFML_KEYTOSTRING_CASE(LBracket)
		SNAKESFML_KEYTOSTRING_CASE(RBracket)
		SNAKESFML_KEYTOSTRING_CASE(SemiColon)
		SNAKESFML_KEYTOSTRING_CASE(Comma)
		SNAKESFML_KEYTOSTRING_CASE(Period)
		SNAKESFML_KEYTOSTRING_CASE(Quote)
		SNAKESFML_KEYTOSTRING_CASE(Slash)
		SNAKESFML_KEYTOSTRING_CASE(BackSlash)
		SNAKESFML_KEYTOSTRING_CASE(Tilde)
		SNAKESFML_KEYTOSTRING_CASE(Equal)
		SNAKESFML_KEYTOSTRING_CASE(Dash)
		SNAKESFML_KEYTOSTRING_CASE(Space)
		SNAKESFML_KEYTOSTRING_CASE(Return)
		SNAKESFML_KEYTOSTRING_CASE(BackSpace)
		SNAKESFML_KEYTOSTRING_CASE(Tab)
		SNAKESFML_KEYTOSTRING_CASE(PageUp)
		SNAKESFML_KEYTOSTRING_CASE(PageDown)
		SNAKESFML_KEYTOSTRING_CASE(End)
		SNAKESFML_KEYTOSTRING_CASE(Home)
		SNAKESFML_KEYTOSTRING_CASE(Insert)
		SNAKESFML_KEYTOSTRING_CASE(Delete)
		SNAKESFML_KEYTOSTRING_CASE(Add)
		SNAKESFML_KEYTOSTRING_CASE(Subtract)
		SNAKESFML_KEYTOSTRING_CASE(Multiply)
		SNAKESFML_KEYTOSTRING_CASE(Divide)
		SNAKESFML_KEYTOSTRING_CASE(Left)
		SNAKESFML_KEYTOSTRING_CASE(Right)
		SNAKESFML_KEYTOSTRING_CASE(Up)
		SNAKESFML_KEYTOSTRING_CASE(Down)
		SNAKESFML_KEYTOSTRING_CASE(Numpad0)
		SNAKESFML_KEYTOSTRING_CASE(Numpad1)
		SNAKESFML_KEYTOSTRING_CASE(Numpad2)
		SNAKESFML_KEYTOSTRING_CASE(Numpad3)
		SNAKESFML_KEYTOSTRING_CASE(Numpad4)
		SNAKESFML_KEYTOSTRING_CASE(Numpad5)
		SNAKESFML_KEYTOSTRING_CASE(Numpad6)
		SNAKESFML_KEYTOSTRING_CASE(Numpad7)
		SNAKESFML_KEYTOSTRING_CASE(Numpad8)
		SNAKESFML_KEYTOSTRING_CASE(Numpad9)
		SNAKESFML_KEYTOSTRING_CASE(F1)
		SNAKESFML_KEYTOSTRING_CASE(F2)
		SNAKESFML_KEYTOSTRING_CASE(F3)
		SNAKESFML_KEYTOSTRING_CASE(F4)
		SNAKESFML_KEYTOSTRING_CASE(F5)
		SNAKESFML_KEYTOSTRING_CASE(F6)
		SNAKESFML_KEYTOSTRING_CASE(F7)
		SNAKESFML_KEYTOSTRING_CASE(F8)
		SNAKESFML_KEYTOSTRING_CASE(F9)
		SNAKESFML_KEYTOSTRING_CASE(F10)
		SNAKESFML_KEYTOSTRING_CASE(F11)
		SNAKESFML_KEYTOSTRING_CASE(F12)
		SNAKESFML_KEYTOSTRING_CASE(F13)
		SNAKESFML_KEYTOSTRING_CASE(F14)
		SNAKESFML_KEYTOSTRING_CASE(F15)
		SNAKESFML_KEYTOSTRING_CASE(Pause)
	}

	return "";
}

void centerOrigin(sf::Sprite& sprite)
{
	sf::FloatRect bounds = sprite.getLocalBounds();
	sprite.setOrigin(std::floor(bounds.left + bounds.width / 2.f), std::floor(bounds.top + bounds.height / 2.f));
}

void centerOrigin(sf::Text& text)
{
	sf::FloatRect bounds = text.getLocalBounds();
	text.setOrigin(std::floor(bounds.left + bounds.width / 2.f), std::floor(bounds.top + bounds.height / 2.f));
}
